### ISSUE TITLE
请问下你的LuaJIT是什么版本？

### ISSUE THREAD

**Issue by huangwei1024** [CheyiLin/ljlz4#1]
我的环境是LuaJIT 2.0.1
`dest_buf + hdr_len` 这种地址计算后的结果传递给C函数时是错误的
不知道是否是LuaJIT版本问题

我在 [这个链接中](http://lua-users.org/lists/lua-l/2011-05/msg00294.html) 也看到类似讨论，实现方法是用`ffi.cast`进行转换。

**Comment by cheyilin** [comment]
是 i386 or x86_64 平台？能否提供錯誤訊息？

在 [lz4.lua:122](https://github.com/CheyiLin/ljlz4/blob/master/lz4.lua#L122) 這段 `dest_buf + hdr_len` 我實測是沒有問題的
可以看一下 [Travis CI](https://travis-ci.org/CheyiLin/ljlz4) 的頁面，LuaJIT 2.0.4 與 2.1 都正常

關於 `dest_buf` 這 `cdata` 的算數計算，我是參考 [FFI Semantics - Arithmetic on cdata objects](http://luajit.org/ext_ffi_semantics.html#cdata_arith)

**Comment by huangwei1024** [comment]
是i386
我的应用场景没有使用dll或so，而是将lz4直接以static lib形式嵌入宿主程序
然后导出C函数给Lua使用
这是该函数代码

```
static int compress(lua_State *L)
{
    char* dest = (char*)lua_topointer(L, 1);
    int destOff = lua_tonumber(L, 2);
    int destLen = lua_tonumber(L, 3);
    const char* src = lua_tostring(L, 4);
    int srcLen = lua_tonumber(L, 5);

    int cpLen = LZ4_compressBound(srcLen);
    if (cpLen > destLen)
    {
        lua_pushnumber(L, -1);
        return 1;
    }

    cpLen = LZ4_compress_limitedOutput(src, dest + destOff, srcLen, destLen);
    lua_pushnumber(L, cpLen);
    return 1;
}
```

我简单测试了下，每次`dest_buf + hdr_len`似乎都会产生的新的cdata，导致压缩数据存放到其它地址，而`dest_buf`原地址上除了`lz4_hdr_t`数据，后面的全为0。
我不清楚lz4.so是否做过相应处理，现在我传入`destOff`是为了能在C中进行正确的指针偏移。
对FFI底层实现不大清楚，求教~

**Comment by cheyilin** [comment]
看來你是混用 Lua C API 與 LuaJIT FFI 了，LuaJIT 作者 Mike 有提示過不能這樣用
供你參考 [Re: Accessing ctype of FFI cdata from the Lua C API](http://www.freelists.org/post/luajit/Accessing-ctype-of-FFI-cdata-from-the-Lua-C-API,1)

**Comment by huangwei1024** [comment]
非常感谢，看来是混用的问题
